import { Inter_Tight } from "next/font/google";

import { Toaster } from "@/components/ui/toaster";

import { i18n } from "@/i18n-config";
import { cn } from "@/lib/utils";

import "../../globals.css";
import Navbar from "./navbar";

const interTight = Inter_Tight({ subsets: ["latin"] });

export const revalidate = 0; // Disable caching

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ locale }));
}

export default function AuthLayout({ children, params: { locale } }) {
  return (
    <html lang={locale}>
      <body className={cn(interTight.className, "min-h-screen bg-customBlue")}>
        <Navbar />
        <div className="flex justify-center px-4 py-[5vh] sm:py-[10vh]">
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}

export const metadata = {
  title: "IT EDUCATION ASSOCIATION",
  description: "Generated by create next app",
};
